import { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import ChartComponent from "../components/ChartComponent";

export default function Dashboard() {

  const [data, setData] = useState({
    clients: 0,
    spend: 0,
    clicks: 0,
    conversions: 0,
    impressions: 1000 // dummy for now
  });

  const [clients, setClients] = useState([]);
  const [loading, setLoading] = useState(true);

  // ✅ FETCH DATA
  useEffect(() => {

    const fetchData = async () => {
      try {
        const token = localStorage.getItem("token");

        // ✅ dashboard API
        const dashRes = await axios.get(
          "http://localhost:5000/api/dashboard",
          {
            headers: { Authorization: token }
          }
        );

        // ✅ clients API
        const clientRes = await axios.get(
          "http://localhost:5000/api/clients",
          {
            headers: { Authorization: token }
          }
        );

        const dashboard = dashRes.data;

        setData({
          clients: dashboard.clients || 0,
          spend: dashboard.spend || 0,
          clicks: dashboard.clicks || 0,
          conversions: dashboard.conversions || 0,
          impressions: 1000
        });

        setClients(clientRes.data || []);

        setLoading(false);

      } catch (err) {
        console.log(err);
        setLoading(false);
      }
    };

    fetchData();

  }, []);

  // 🔢 Calculations
  const ctr = ((data.clicks / data.impressions) * 100).toFixed(2);
  const cpc = (data.spend / (data.clicks || 1)).toFixed(2);
  const cpa = (data.spend / (data.conversions || 1)).toFixed(2);

  // ✅ GLOBAL PDF
  const downloadPDF = async () => {

    const pdf = new jsPDF("p", "mm", "a4");

    // ✅ COVER PAGE
    pdf.setFontSize(24);
    pdf.text("Marketing Report", 60, 80);

    pdf.setFontSize(16);
    pdf.text("Generated by: Report Generator", 50, 100);

    const today = new Date().toLocaleDateString();
    pdf.text("Date: " + today, 70, 120);

    pdf.text("Total Clients: " + data.clients, 65, 140);

    // ✅ NEW PAGE
    pdf.addPage();

    const input = document.getElementById("dashboard-content");
    const canvas = await html2canvas(input);
    const imgData = canvas.toDataURL("image/png");

    const imgWidth = 190;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 10, 10, imgWidth, imgHeight);

    pdf.save("Marketing_Report.pdf");
  };

  // ✅ CLIENT PDF
  const downloadClientPDF = async (id, name) => {

    const element = document.getElementById(`client-${id}`);

    const canvas = await html2canvas(element);
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");

    pdf.setFontSize(18);
    pdf.text(`Client Report: ${name}`, 20, 20);

    pdf.addImage(imgData, "PNG", 10, 30, 180, 120);

    pdf.save(`${name}_Report.pdf`);
  };

  if (loading) return <h2 style={{ padding: 20 }}>Loading dashboard...</h2>;

  return (
    <div style={{ padding: 20 }}>

      {/* 🔥 FILTERS */}
      <div style={{ marginBottom: 20 }}>
        <input type="date" />
        <select>
          <option>All Clients</option>
        </select>
        <select>
          <option>Meta Ads</option>
          <option>Google Ads</option>
        </select>
      </div>

      {/* 🔥 PDF BUTTON */}
      <button
        onClick={downloadPDF}
        style={{
          padding: 10,
          background: "black",
          color: "white",
          borderRadius: 8,
          marginBottom: 20
        }}
      >
        Download Full Report
      </button>

      {/* ✅ DASHBOARD */}
      <div id="dashboard-content">

        <h1>Marketing Dashboard</h1>

        {/* ✅ CARDS */}
        <div style={{
          display: "flex",
          gap: 20,
          marginTop: 20,
          flexWrap: "wrap"
        }}>
          <Card title="Clients" value={data.clients} />
          <Card title="Spend" value={"₹" + data.spend} />
          <Card title="Clicks" value={data.clicks} />
          <Card title="Conversions" value={data.conversions} />
          <Card title="Impressions" value={data.impressions} />
          <Card title="CTR" value={ctr + "%"} />
          <Card title="CPC" value={"₹" + cpc} />
          <Card title="CPA" value={"₹" + cpa} />
        </div>

        {/* ✅ GRAPH */}
        <div style={{ marginTop: 30 }}>
          <ChartComponent />
        </div>

      </div>

      {/* 🔥 CLIENT SECTION */}
      <h2 style={{ marginTop: 40 }}>Client Reports</h2>

      <div style={{ display: "flex", flexWrap: "wrap" }}>

        {clients.map(client => (
          <div key={client._id} style={{
            border: "1px solid #ddd",
            padding: 20,
            margin: 20,
            borderRadius: 10,
            width: 300
          }}>

            <h3>{client.name}</h3>
            <p>Spend: ₹{client.spend || 0}</p>
            <p>Clicks: {client.clicks || 0}</p>
            <p>Conversions: {client.conversions || 0}</p>

            {/* ✅ PDF CONTENT */}
            <div id={`client-${client._id}`}>
              <h3>{client.name}</h3>
              <p>Spend: ₹{client.spend || 0}</p>
              <p>Clicks: {client.clicks || 0}</p>
              <p>Conversions: {client.conversions || 0}</p>

              <ChartComponent client={client} />
            </div>

            {/* ✅ BUTTON */}
            <button
              onClick={() => downloadClientPDF(client._id, client.name)}
              style={{
                marginTop: 10,
                padding: 8,
                background: "blue",
                color: "white",
                borderRadius: 6
              }}
            >
              Download PDF
            </button>

          </div>
        ))}

      </div>

    </div>
  );
}

// ✅ CARD COMPONENT
function Card({ title, value }) {
  return (
    <div style={{
      border: "1px solid #ddd",
      borderRadius: 12,
      padding: 20,
      width: 200,
      background: "#f7f9fc",
      boxShadow: "0 2px 6px rgba(0,0,0,0.05)"
    }}>
      <h3 style={{ marginBottom: 10 }}>{title}</h3>
      <h2>{value}</h2>
    </div>
  );
}